name: Build

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/MongoQ.sln
    - name: Build
      run: dotnet build src/MongoQ.sln --no-restore
    - name: Test
      run: dotnet test src/MongoQ.Tests/MongoQ.Tests.csproj --no-build
    - name: Pack MongoQ
      run: dotnet pack src/MongoQ/MongoQ.csproj --no-build -p:PackageVersion=0.1.${{github.run_number}}
   # - name: Test
   #   run: dotnet test --no-build --verbosity normal
