name: pull-request-gate

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build-gate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/MinimalMongo.sln

    - name: Build MinimalMongo
      run: dotnet build src/MinimalMongo/MinimalMongo.csproj -c Release --no-restore -f netstandard2.0

    - name: Build MinimalMongo.AspNetCore
      run: dotnet build src/MinimalMongo.AspNetCore/MinimalMongo.AspNetCore.csproj -c Release --no-restore -f netstandard2.0
      
    - name: Test
      run: dotnet test src/MinimalMongo.Tests/MinimalMongo.Tests.csproj -c Release