name: pull-request-gate

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/MongoQ.sln
    - name: Build
      run: dotnet build src/MongoQ.sln -c Release --no-restore
    - name: Test
      run: dotnet test src/MongoQ.Tests/MongoQ.Tests.csproj -c Release --no-build
    - name: Pack MongoQ Nuget
      run: dotnet pack src/MongoQ/MongoQ.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_id}}
    - name: Pack MongoQ.AspNetCore Nuget
      run: dotnet pack src/MongoQ.AspNetCore/MongoQ.AspNetCore.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_id}}
   # - name: Test
   #   run: dotnet test --no-build --verbosity normal
