name: CD-Build

on:
  push:
    # Runs on all branches so they share a github.run_number increment
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/MinimalMongo.sln
      
    - name: Build MinimalMongo
      run: dotnet build src/MinimalMongo/MinimalMongo.csproj -c Release --no-restore -f netstandard2.0

    - name: Build MinimalMongo.AspNetCore
      run: dotnet build src/MinimalMongo.AspNetCore/MinimalMongo.AspNetCore.csproj -c Release --no-restore -f netstandard2.0
      
    - name: Test
      run: dotnet test src/MinimalMongo.Tests/MinimalMongo.Tests.csproj -c Release
      
      # packs all nuget packages at once 
    - name: Pack MinimalMongo Nuget Alpha
      run: dotnet pack src/MinimalMongo/MinimalMongo.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_number}}-alpha
    - name: Pack MinimalMongo Nuget
      run: dotnet pack src/MinimalMongo/MinimalMongo.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_number}}
    - name: Pack MinimalMongo.AspNetCore Nuget Alpha
      run: dotnet pack src/MinimalMongo.AspNetCore/MinimalMongo.AspNetCore.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_number}}-alpha
    - name: Pack MinimalMongo.AspNetCore Nuget
      run: dotnet pack src/MinimalMongo.AspNetCore/MinimalMongo.AspNetCore.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_number}}
      
    - name: Publish MinimalMongo Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Nugets
        path: src/**/bin/**/*.nupkg
        
  integration:
    needs: build
    name: Deploy Nuget-alpha packages
    environment:
      name: Integration
    runs-on: ubuntu-latest
    steps:
    - name: Download nugets
      uses: actions/download-artifact@v2
      with:
        name: Nugets
      
      
    - name: Display structure of downloaded files
      run: ls -R
    - name: Push MinimalMongo Nuget
      run: dotnet nuget push ./MinimalMongo/bin/Release/MinimalMongo.0.1.${{github.run_number}}-alpha.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json
    - name: Push MinimalMongo.AspNetCore Nuget
      run: dotnet nuget push ./MinimalMongo.AspNetCore/bin/Release/MinimalMongo.AspNetCore.0.1.${{github.run_number}}-alpha.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json

  production:
    needs: integration
    name: Deploy Nuget packages to production
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
    - name: Download nugets
      uses: actions/download-artifact@v2
      with:
        name: Nugets
        
    - name: Push MinimalMongo Nuget
      run: dotnet nuget push ./MinimalMongo/bin/Release/MinimalMongo.0.1.${{github.run_number}}.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json
    - name: Push MinimalMongo.AspNetCore Nuget
      run: dotnet nuget push ./MinimalMongo.AspNetCore/bin/Release/MinimalMongo.AspNetCore.0.1.${{github.run_number}}.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json

