name: pull-request-gate

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build-gate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/MongoQ.sln

    - name: Build MongoQ
      run: dotnet build src/MongoQ/MongoQ.csproj -c Release --no-restore -f netstandard2.0

    - name: Build MongoQ.AspNetCore
      run: dotnet build src/MongoQ.AspNetCore/MongoQ.AspNetCore.csproj -c Release --no-restore -f netstandard2.0
      
    - name: Test
      run: dotnet test src/MongoQ.Tests/MongoQ.Tests.csproj -c Release