name: CD-Build

on:
  push:
    # Runs on all branches so they share a github.run_number increment
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/MongoQ.sln
      
    - name: Build
      run: dotnet build src/MongoQ.sln -c Release --no-restore
      
    - name: Test
      run: dotnet test src/MongoQ.Tests/MongoQ.Tests.csproj -c Release --no-build
      
      # packs all nuget packages at once 
    - name: Pack MongoQ Nuget Alpha
      run: dotnet pack src/MongoQ/MongoQ.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_number}}-alpha
    - name: Pack MongoQ Nuget
      run: dotnet pack src/MongoQ/MongoQ.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_number}}
    - name: Pack MongoQ.AspNetCore Nuget Alpha
      run: dotnet pack src/MongoQ.AspNetCore/MongoQ.AspNetCore.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_number}}-alpha
    - name: Pack MongoQ.AspNetCore Nuget
      run: dotnet pack src/MongoQ.AspNetCore/MongoQ.AspNetCore.csproj -c Release --no-build -p:PackageVersion=0.1.${{github.run_number}}
      
    - name: Publish MongoQ Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Nugets
        path: src/**/bin/**/*.nupkg
        
  integration:
    needs: build
    name: Deploy Nuget-alpha packages
    environment:
      name: Integration
    runs-on: ubuntu-latest
    steps:
    - name: Download nugets
      uses: actions/download-artifact@v2
      with:
        name: Nugets
      
      
    - name: Display structure of downloaded files
      run: ls -R
    - name: Push MongoQ Nuget
      run: dotnet nuget push ./MongoQ/bin/Release/MongoQ.0.1.${{github.run_number}}-alpha.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json
    - name: Push MongoQ.AspNetCore Nuget
      run: dotnet nuget push ./MongoQ.AspNetCore/bin/Release/MongoQ.AspNetCore.0.1.${{github.run_number}}-alpha.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json

  production:
    needs: integration
    name: Deploy Nuget packages to production
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
    - name: Download nugets
      uses: actions/download-artifact@v2
      with:
        name: Nugets
        
    - name: Push MongoQ Nuget
      run: dotnet nuget push ./MongoQ/bin/Release/MongoQ.0.1.${{github.run_number}}.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json
    - name: Push MongoQ.AspNetCore Nuget
      run: dotnet nuget push ./MongoQ.AspNetCore/bin/Release/MongoQ.AspNetCore.0.1.${{github.run_number}}.nupkg --api-key ${{secrets.NUGETKEY}} --source https://api.nuget.org/v3/index.json

